//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomPilot.Language {
    using System;
    
    
    /// <summary>
    ///   지역화된 문자열 등을 찾기 위한 강력한 형식의 리소스 클래스입니다.
    /// </summary>
    // 이 클래스는 ResGen 또는 Visual Studio와 같은 도구를 통해 StronglyTypedResourceBuilder
    // 클래스에서 자동으로 생성되었습니다.
    // 멤버를 추가하거나 제거하려면 .ResX 파일을 편집한 다음 /str 옵션을 사용하여 ResGen을
    // 다시 실행하거나 VS 프로젝트를 다시 빌드하십시오.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Languages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Languages() {
        }
        
        /// <summary>
        ///   이 클래스에서 사용하는 캐시된 ResourceManager 인스턴스를 반환합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomPilot.Language.Languages", typeof(Languages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   이 강력한 형식의 리소스 클래스를 사용하여 모든 리소스 조회에 대한 현재 스레드의 CurrentUICulture
        ///   속성을 재정의합니다.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Custompilot Software Info과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string FORM_ABOUT_CAPTION {
            get {
                return ResourceManager.GetString("FORM_ABOUT_CAPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Clear과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_CLEAR {
            get {
                return ResourceManager.GetString("MENU_CLEAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Connect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_CONNECT {
            get {
                return ResourceManager.GetString("MENU_CONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnect과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_DISCONNECT {
            get {
                return ResourceManager.GetString("MENU_DISCONNECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit(&amp;X)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_EXIT {
            get {
                return ResourceManager.GetString("MENU_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_EXPORT {
            get {
                return ResourceManager.GetString("MENU_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Factory Reset과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_FACTORYRESET {
            get {
                return ResourceManager.GetString("MENU_FACTORYRESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File(&amp;F)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_FILE {
            get {
                return ResourceManager.GetString("MENU_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firmware Ver:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_FIRMWAREVER {
            get {
                return ResourceManager.GetString("MENU_FIRMWAREVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Help(&amp;H)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_HELP {
            get {
                return ResourceManager.GetString("MENU_HELP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   About custompilot(&amp;A)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_HELP_ABOUT {
            get {
                return ResourceManager.GetString("MENU_HELP_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Install USB Driver과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_HELP_DRIVER {
            get {
                return ResourceManager.GetString("MENU_HELP_DRIVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Support Online(&amp;O)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_HELP_SUPPORT {
            get {
                return ResourceManager.GetString("MENU_HELP_SUPPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   IMU과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_IMU {
            get {
                return ResourceManager.GetString("MENU_IMU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_IMU_CAL {
            get {
                return ResourceManager.GetString("MENU_IMU_CAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open(&amp;O)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_OPEN {
            get {
                return ResourceManager.GetString("MENU_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report(&amp;R)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_REPORT {
            get {
                return ResourceManager.GetString("MENU_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save(&amp;S)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_SAVE {
            get {
                return ResourceManager.GetString("MENU_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Setting(&amp;S)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MENU_SETTING {
            get {
                return ResourceManager.GetString("MENU_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MESSAGE_ALERT {
            get {
                return ResourceManager.GetString("MESSAGE_ALERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MESSAGE_CANCEL {
            get {
                return ResourceManager.GetString("MESSAGE_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select COM port과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MESSAGE_COM_SELECT {
            get {
                return ResourceManager.GetString("MESSAGE_COM_SELECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MESSAGE_ERROR {
            get {
                return ResourceManager.GetString("MESSAGE_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MESSAGE_NO {
            get {
                return ResourceManager.GetString("MESSAGE_NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This operation overwrites the data on the connected device.
        ///Do you want to continue?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MESSAGE_OVERWRITE_CPM {
            get {
                return ResourceManager.GetString("MESSAGE_OVERWRITE_CPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning!\nAll reports will be deleted.\nData can not be recovered.\nDo you really want to delete?과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MESSAGE_WARNING_REPORT_RESET {
            get {
                return ResourceManager.GetString("MESSAGE_WARNING_REPORT_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Yes과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string MESSAGE_YES {
            get {
                return ResourceManager.GetString("MESSAGE_YES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Console과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_CONSOLE {
            get {
                return ResourceManager.GetString("PAGE_FIRM_CONSOLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Disconnected과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_DISCONNECTED {
            get {
                return ResourceManager.GetString("PAGE_FIRM_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Download과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_DOWNLOAD {
            get {
                return ResourceManager.GetString("PAGE_FIRM_DOWNLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_FILE {
            get {
                return ResourceManager.GetString("PAGE_FIRM_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   firmware:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_FIRMWARE {
            get {
                return ResourceManager.GetString("PAGE_FIRM_FIRMWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firmware Backup과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_FIRMWAREBACKUP {
            get {
                return ResourceManager.GetString("PAGE_FIRM_FIRMWAREBACKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firmware upload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_FIRMWAREUPLOAD {
            get {
                return ResourceManager.GetString("PAGE_FIRM_FIRMWAREUPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Board Information과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_INFORMATION {
            get {
                return ResourceManager.GetString("PAGE_FIRM_INFORMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   name:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_NAME {
            get {
                return ResourceManager.GetString("PAGE_FIRM_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Open과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_OPEN {
            get {
                return ResourceManager.GetString("PAGE_FIRM_OPEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   product id:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_PRODUCTID {
            get {
                return ResourceManager.GetString("PAGE_FIRM_PRODUCTID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_SAVE {
            get {
                return ResourceManager.GetString("PAGE_FIRM_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_SET {
            get {
                return ResourceManager.GetString("PAGE_FIRM_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   state:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_STATE {
            get {
                return ResourceManager.GetString("PAGE_FIRM_STATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Upload과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_UPLOAD {
            get {
                return ResourceManager.GetString("PAGE_FIRM_UPLOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ver:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_FIRM_VER {
            get {
                return ResourceManager.GetString("PAGE_FIRM_VER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode1:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_A {
            get {
                return ResourceManager.GetString("PAGE_MODE_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode2:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_B {
            get {
                return ResourceManager.GetString("PAGE_MODE_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode3:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_C {
            get {
                return ResourceManager.GetString("PAGE_MODE_C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_DEFAULT {
            get {
                return ResourceManager.GetString("PAGE_MODE_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hovering과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_HOVERING {
            get {
                return ResourceManager.GetString("PAGE_MODE_HOVERING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Knife edge과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_KNIFEEDGE {
            get {
                return ResourceManager.GetString("PAGE_MODE_KNIFEEDGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Manual과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_MANUAL {
            get {
                return ResourceManager.GetString("PAGE_MODE_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_MIX {
            get {
                return ResourceManager.GetString("PAGE_MODE_MIX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mode Channels과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_MODECHANNELS {
            get {
                return ResourceManager.GetString("PAGE_MODE_MODECHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reverse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_REVERSE {
            get {
                return ResourceManager.GetString("PAGE_MODE_REVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flight mode setting과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_SETTING {
            get {
                return ResourceManager.GetString("PAGE_MODE_SETTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stabilize과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_STABILIZE {
            get {
                return ResourceManager.GetString("PAGE_MODE_STABILIZE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Stabilize2과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_STABILIZE2 {
            get {
                return ResourceManager.GetString("PAGE_MODE_STABILIZE2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Take off과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MODE_TAKEOFF {
            get {
                return ResourceManager.GetString("PAGE_MODE_TAKEOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Backward과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MOUNT_BACK {
            get {
                return ResourceManager.GetString("PAGE_MOUNT_BACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Bottom과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MOUNT_BOTTOM {
            get {
                return ResourceManager.GetString("PAGE_MOUNT_BOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Front과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MOUNT_FRONT {
            get {
                return ResourceManager.GetString("PAGE_MOUNT_FRONT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FRONT / BACKWARD과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MOUNT_FRONTBACK {
            get {
                return ResourceManager.GetString("PAGE_MOUNT_FRONTBACK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mount과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MOUNT_NAME {
            get {
                return ResourceManager.GetString("PAGE_MOUNT_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Top과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MOUNT_TOP {
            get {
                return ResourceManager.GetString("PAGE_MOUNT_TOP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TOP / BOTTOM과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_MOUNT_TOPBOTTOM {
            get {
                return ResourceManager.GetString("PAGE_MOUNT_TOPBOTTOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Revcerse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_OTUPTU_REVERSE {
            get {
                return ResourceManager.GetString("PAGE_OTUPTU_REVERSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_OTUPUT_OUTPUT {
            get {
                return ResourceManager.GetString("PAGE_OTUPUT_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Center과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_OUTPUT_CENTER {
            get {
                return ResourceManager.GetString("PAGE_OUTPUT_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Channel과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_OUTPUT_CHANNEL {
            get {
                return ResourceManager.GetString("PAGE_OUTPUT_CHANNEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_OUTPUT_DEFAULT {
            get {
                return ResourceManager.GetString("PAGE_OUTPUT_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Max과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_OUTPUT_MAX {
            get {
                return ResourceManager.GetString("PAGE_OUTPUT_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Min과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_OUTPUT_MIN {
            get {
                return ResourceManager.GetString("PAGE_OUTPUT_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Pulse과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_OUTPUT_PULSE {
            get {
                return ResourceManager.GetString("PAGE_OUTPUT_PULSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_OUTPUT_SAVE {
            get {
                return ResourceManager.GetString("PAGE_OUTPUT_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Calibration과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_RADIO_CALIBRATION {
            get {
                return ResourceManager.GetString("PAGE_RADIO_CALIBRATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CENTER:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_RADIO_CENTER {
            get {
                return ResourceManager.GetString("PAGE_RADIO_CENTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_RADIO_DEFAULT {
            get {
                return ResourceManager.GetString("PAGE_RADIO_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input channels과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_RADIO_INPUTCHANNELS {
            get {
                return ResourceManager.GetString("PAGE_RADIO_INPUTCHANNELS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MAX:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_RADIO_MAX {
            get {
                return ResourceManager.GetString("PAGE_RADIO_MAX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   MIN:과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_RADIO_MIN {
            get {
                return ResourceManager.GetString("PAGE_RADIO_MIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Protocol과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_RADIO_PROTOCOL {
            get {
                return ResourceManager.GetString("PAGE_RADIO_PROTOCOL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Radio signal HZ과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_RADIO_RADIOHZ {
            get {
                return ResourceManager.GetString("PAGE_RADIO_RADIOHZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_RADIO_SAVE {
            get {
                return ResourceManager.GetString("PAGE_RADIO_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Count과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_REPORTS_COUNT {
            get {
                return ResourceManager.GetString("PAGE_REPORTS_COUNT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Export(&amp;E)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_REPORTS_EXPORT {
            get {
                return ResourceManager.GetString("PAGE_REPORTS_EXPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FID과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_REPORTS_FID {
            get {
                return ResourceManager.GetString("PAGE_REPORTS_FID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reports과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_REPORTS_REPORTS {
            get {
                return ResourceManager.GetString("PAGE_REPORTS_REPORTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reset(&amp;R)과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_REPORTS_RESET {
            get {
                return ResourceManager.GetString("PAGE_REPORTS_RESET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WDT과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string PAGE_REPORTS_WDT {
            get {
                return ResourceManager.GetString("PAGE_REPORTS_WDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Board과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TAB_BOARD {
            get {
                return ResourceManager.GetString("TAB_BOARD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Firmware과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TAB_FIRMWARE {
            get {
                return ResourceManager.GetString("TAB_FIRMWARE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Flight mode과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TAB_MODE {
            get {
                return ResourceManager.GetString("TAB_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TAB_OUTPUT {
            get {
                return ResourceManager.GetString("TAB_OUTPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Radio과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TAB_RADIO {
            get {
                return ResourceManager.GetString("TAB_RADIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Report과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TAB_REPORT {
            get {
                return ResourceManager.GetString("TAB_REPORT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sensor과(와) 유사한 지역화된 문자열을 찾습니다.
        /// </summary>
        internal static string TAB_SENSOR {
            get {
                return ResourceManager.GetString("TAB_SENSOR", resourceCulture);
            }
        }
    }
}
